### ISSUE TITLE
The count of reviews includes unpublished reviews

### ISSUE THREAD

**Issue by rmanger** [asd-schools/asd-schools#16]
Steps to repro:
- Search for school
- Create a review 
- Go back to search results page that includes that school
  - Count of reviews displays correctly
- In the admin site, unpublish the review
- Go back to search results page that includes that school
  - Count of reviews has not changed

Seems a little wierd clicking through to view a review that doesn't appear to exist.

**Comment by DanielHeath** [comment]
Fixed
