### ISSUE TITLE
Server error when attempting to search with an empty locations field

### ISSUE THREAD

**Issue by rmanger** [asd-schools/asd-schools#6]
If you click search on the homepage without entering a location you get a server error.

Error on server:
`Parameters: {"search"=>{"atlas_id"=>"", "autism_classification"=>"Autism Classification", "lat"=>"", "lng"=>"", "school_type"=>"Type", "sector"=>"Sector", "suburb"=>""}} Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)`
`ArgumentError (invalid value for Float(): ""):`

**Comment by rmanger** [comment]
Error on server:
```  Parameters: {"search"=>{"atlas_id"=>"", "autism_classification"=>"Autism Classification", "lat"=>"", "lng"=>"", "school_type"=>"Type", "sector"=>"Sector", "suburb"=>""}}
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)
ArgumentError (invalid value for Float(): ""):```

**Comment by DanielHeath** [comment]
Fixed
